<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EmSystem7" failures="1" tests="5" name="com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI" time="2.850" errors="0" timestamp="2021-01-22T21:54:26 EST" skipped="4">
  <testcase classname="com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI" name="validateCreateCustomerAPIWithInValidAuthKey" time="0.514">
    <skipped/>
  </testcase> <!-- validateCreateCustomerAPIWithInValidAuthKey -->
  <system-out/>
  <testcase classname="com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI" name="validateCreateCustomerAPIWithValidData" time="2.336">
    <failure message="expected [200] but found [400]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:617)
at com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI.validateCreateCustomerAPIWithValidData(TestCustomerAPI.java:115)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- validateCreateCustomerAPIWithValidData -->
  <system-out/>
  <testcase classname="com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI" name="validateCreateCustomerAPIWithoutPassingAuthKey" time="0.000">
    <skipped/>
  </testcase> <!-- validateCreateCustomerAPIWithoutPassingAuthKey -->
  <system-out/>
  <testcase classname="com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI" name="validateCreateCustomerAPIWithInvalidField" time="0.000">
    <skipped/>
  </testcase> <!-- validateCreateCustomerAPIWithInvalidField -->
  <system-out/>
  <testcase classname="com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI" name="validateCreateCustomerAPIWithInValidEmail" time="0.000">
    <skipped/>
  </testcase> <!-- validateCreateCustomerAPIWithInValidEmail -->
  <system-out/>
</testsuite> <!-- com.e7.specFrame.API_FrameWork.testcases.TestCustomerAPI -->
